services:
  sonarqube:
    image: sonarqube:9.9.8-community
    restart: always
    env_file:
      - .env
      - app/.env
    ports:
      - 9000:9000
    volumes:
      - ./app/plugin:/opt/sonarqube/extensions/plugins
    networks:
      - sonar_network

  sonar-scanner-cli:
    image: sonarsource/sonar-scanner-cli:11.2.1.1844_7.0.2
    user: root
    restart: always
    env_file:
      - .env
      - app/.env
    volumes:
      - ./app/tmp/scanner_cache:/opt/sonar-scanner/.sonar/cache
    networks:
      - sonar_network
    depends_on:
      - sonarqube

networks:
  sonar_network:
    driver: bridge
